blog/urls.py
# coding: utf-8

from rest_framework import routers
from .views import UserViewSet, EntryViewSet, CustomUserViewSet

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'custom-users', CustomUserViewSet)
router.register(r'entries', EntryViewSet)

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from blog.urls import router as blog_router

from django.conf.urls import include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),

    # blog.urlsをincludeする
    url(r'^api/', include(blog_router.urls))
]

polls/urls.py
from django.urls import path

from . import views

# 名前空間を追加
app_name = 'polls'

urlpatterns = [
    # ex: /polls
    # path('', views.index, name='index'),
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    # path('<int:question_id>/', views.detail, name='detail'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    #path('<int:question_id>/results/', views.results, name='results'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

blog/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    name = models.CharField(max_length=32)
    mail = models.EmailField()
    
    def __str__(self):
        # 主キーとnameを表示させて見やすくする
        # ex) 1: Alice
        return f"{self.pk}, {self.name}"

class Entry(models.Model):
    STATUS_DRAFT = "draft"
    STATUS_PUBLIC = "public"
    STATUS_SET = (
        (STATUS_DRAFT, "下書き"),
        (STATUS_PUBLIC, "公開中"),
    )
    title = models.CharField(max_length=128)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(choices=STATUS_SET, default=STATUS_DRAFT, max_length=8)
    author = models.ForeignKey(User, related_name='entries', on_delete=models.CASCADE)

polls/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
            now = timezone.now()
            return now - datetime.timedelta(days=1) <= self.pub_date <= now

    # Adminでの表示を変更したり結果でソートできるようにする
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?' 
    # 詳しくはlist_displayを参照

# choiceモデル
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text 

blog/views.py
from django.shortcuts import render

# Create your views here.

import django_filters
from rest_framework import viewsets, filters

from .models import User, Entry
from .serializer import UserSerializer, EntrySerializer, CustomUserSerializer

class UserViewSet(viewsets.ModelViewSet):
    # ここでfilterをかけてやれば大丈夫
    queryset = User.objects.all()
    serializer_class = UserSerializer

class CustomUserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.filter(name="pokotsun")
    serializer_class = CustomUserSerializer

class EntryViewSet(viewsets.ModelViewSet):
    queryset = Entry.objects.all()
    serializer_class = EntrySerializer
    filter_fields = ('author', 'status')

polls/views.py
from django.shortcuts import render

from django.http import HttpResponse
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views import generic
from django.utils import timezone


from .models import Question


# Create your views here.
#def index(request):
#    # return HttpResponse("Hello, world. You're at the polls index.")
#    latest_question_list = Question.objects.order_by('-pub_date')[:5]
#
#    # 下と同義
#    #template = loader.get_template('polls/index.html')
#    #context = {
#    #    'latest_question_list': latest_question_list,
#    #}
#    #return HttpResponse(template.render(context, request))
#
#    context = {'latest_question_list': latest_question_list}
#    return render(request, 'polls/index.html', context)
#
#def detail(request, question_id):
#    # 下と同義
#    # get_list_or_404()という関数もある
#    #try:
#    #    question = Question.objects.get(pk=question_id)
#    #except Question.DoesNotExist:
#    #    raise Http404("Question does not exist")
#    question = get_object_or_404(Question, pk=question_id)
#    return render(request, 'polls/detail.html', {'question': question})
#
#def results(request, question_id):
#    question = get_object_or_404(Question, pk=question_id)
#    return render(request, 'polls/results.html', { 'question': question })
#    #response = f"You're looking at the results of question {question_id}"
#    #return HttpResponse(response)
#    #return HttpResponse(response, question_id)

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    #def get_queryset(self):
    #    """Return the last five published questions."""
    #    return Question.objects.order_by('-pub_date')[:5]
    def get_queryset(self): 
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    
    def get_query_set(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist): # request.POST['choice']が存在しなければ
        # Redisplay the question voting home
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/detail.html
{% load static %}
<link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">
<h1>{{ question.question_text }}</h1>
{% if error_message %} <p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" class="btn btn-primary" value="Vote" />
</form>

polls/templates/polls/index.html
{% extends "base.html" %}
{% load static %}
{% block contents %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <!-- 下と同義 -->
        <!-- <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li> -->
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock contents %}

polls/templates/polls/results.html
<h1>{{question.question_text}}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote agein?</a>

templates/base.html
<div class="container">
    <div class="starter-template">
        <h1>Bootstrap starter template</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
    </div>
    {% block contents %}{% endblock %}

</div><!-- /.container -->